version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - "6379:6379"

volumes:
  mongo_data: