export const RESCUE_TEAM_TYPES = {
    AMBULANCE: 'AMBULANCE',
    TOW_TRUCK: 'TOW_TRUCK',
    FIRE: 'FIRE',
    POLICE: 'POLICE',
    MULTI: 'MULTI'
};

export const RESCUE_TEAM_STATUS = {
    AVAILABLE: 'AVAILABLE',
    BUSY: 'BUSY',
    OFFLINE: 'OFFLINE'
};

export const TEAM_CAPABILITIES = {
    FIRST_AID: 'FIRST_AID',
    TOWING: 'TOWING',
    FIRE_FIGHTING: 'FIRE_FIGHTING',
    WATER_RESCUE: 'WATER_RESCUE',
    GENERAL: 'GENERAL'
};

export const ALL_RESCUE_TYPES = Object.values(RESCUE_TEAM_TYPES)
export const ALL_RESCUE_STATUS = Object.values(RESCUE_TEAM_STATUS)
export const ALL_CAPABILITIES = Object.values(TEAM_CAPABILITIES);
