const INCIDENT_TYPES = {
    ACCIDENT: 'ACCIDENT',
    BREAKDOWN: 'BREAKDOWN',
    FLOOD: 'FLOOD',
    FIRE: 'FIRE',
    OTHER: 'OTHER'
};

const INCIDENT_STATUS = {
    PENDING: 'PENDING',
    ASSIGNED: 'ASSIGNED',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED'
};

const INCIDENT_SEVERITY = {
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH',
    CRITICAL: 'CRITICAL'
};

module.exports = {
    INCIDENT_TYPES,
    INCIDENT_STATUS,
    INCIDENT_SEVERITY,
    
    ALL_TYPES: Object.values(INCIDENT_TYPES),
    ALL_STATUS: Object.values(INCIDENT_STATUS),
    ALL_SEVERITIES: Object.values(INCIDENT_SEVERITY)
};